### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Takhmina175** [Takhmina175/Todo-list#2]

**Comment by herokudev** [comment]
Good job so far, try to implement import functions from other files.

**Comment by alef-garrido** [comment]
You're really close Mina! I respect the fact that you are trying to make your own take on this challenge without copying or molding anyone else's code, i'm the same way and i had no problems taking my time to make sure i'm learning. 
My only recommendation could be that you may try to build the functionalities in the order that microverse is suggesting, some of the last functions will use other function that were a requirement in the previous milestone in order to work properly. I'm sure you can do this!

**Comment by Takhmina175** [comment]
> Good job so far, try to implement import functions from other files.

Thank you for your review.

**Comment by Takhmina175** [comment]
> You're really close Mina! I respect the fact that you are trying to make your own take on this challenge without copying or molding anyone else's code, i'm the same way and i had no problems taking my time to make sure i'm learning.
> My only recommendation could be that you may try to build the functionalities in the order that microverse is suggesting, some of the last functions will use other function that were a requirement in the previous milestone in order to work properly. I'm sure you can do this!

Thank you for your suggestions and support!
